NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3,],[4,5,6,],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.ones((4,4,))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.31821791, 0.09098333, 0.7463297 , 0.83577135, 0.69332491])

In [13]:
np.random.randn(2)

array([-0.70506805, -0.12027761])

In [15]:
np.random.randint(1,50,10)

array([10, 22, 25,  6, 27, 29, 13,  5, 42, 40])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0,50,10)

In [19]:
ranarr

array([23,  0,  3, 29, 15, 29,  1, 49, 32, 22])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
ranarr

array([23,  0,  3, 29, 15, 29,  1, 49, 32, 22])

In [22]:
ranarr.max()

49

In [23]:
ranarr.min()

0

In [24]:
ranarr.argmax()

7

In [25]:
ranarr.argmin()

1

In [26]:
arr.shape

(25,)

In [27]:
arr = arr.reshape(5,5)

In [28]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr.shape

(5, 5)

In [30]:
arr.dtype

dtype('int32')

In [31]:
from numpy.random import randint

In [32]:
randint(2,10)

8

INDEXING

In [33]:
var = np.arange(0,5)

In [49]:
var

array([[ 6, 25, 20,  6],
       [16,  1, 38, 29],
       [ 0, 39, 32, 44],
       [ 8, 30, 48, 17]])

In [40]:
print(var[-5])
print(var.ndim)

0
1


In [41]:
var = np.random.randint(0,50,16)

In [42]:
var

array([ 6, 25, 20,  6, 16,  1, 38, 29,  0, 39, 32, 44,  8, 30, 48, 17])

In [43]:
var = var.reshape(4,4)

In [44]:
var

array([[ 6, 25, 20,  6],
       [16,  1, 38, 29],
       [ 0, 39, 32, 44],
       [ 8, 30, 48, 17]])

In [45]:
print(var.ndim)

2


SLICING

In [46]:
print(var[1:5])

[[16  1 38 29]
 [ 0 39 32 44]
 [ 8 30 48 17]]


In [54]:
print(var[::-1])
var[3,0:]

[[ 8 30 48 17]
 [ 0 39 32 44]
 [16  1 38 29]
 [ 6 25 20  6]]


array([ 8, 30, 48, 17])

In [50]:
print(var[::2])

[[ 6 25 20  6]
 [ 0 39 32 44]]


In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[0:4]

array([0, 1, 2, 3])

In [60]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[0:4] = 100

In [62]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [63]:
arr_copy = arr.copy()

In [64]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [65]:
arr_copy

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [66]:
arr_copy[:] = 1000

In [67]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [68]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [7]:
arr_2d = np.arange(0,9)
arr_2d = arr_2d.reshape(3,3)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr_2d[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr_2d[2:]

array([[6, 7, 8]])

In [10]:
arr_2d[1:,1:]

array([[4, 5],
       [7, 8]])

In [15]:
arr = np.random.randint(0,50,20)
bool_arr = arr > 15
bool_arr
# arr[bool_arr]

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True, False, False, False, False,  True, False,
       False, False])

In [16]:
arr[arr<3]

array([0, 1])

In [18]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [22]:
arr_2d[2:3]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

OPERATIONS IN NUMPY

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr * arr
arr+100
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
np.max(arr)

9

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.log(arr)

C:\Users\samundra\AppData\Local\Temp\ipykernel_7968\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

 'NumPy Exercises'

In [28]:
#create an array of 10 zeros
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [31]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [33]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [56]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.random.rand(1)

array([0.0991525])

In [46]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#use numpy to generate an array of 35 random numbers sampled from a 
#standard normal distribution
np.random.normal(0,1,25)

array([ 0.7539623 , -0.01869069, -1.72752484, -1.60274094,  1.42593198,
       -2.04103871,  2.39592391,  0.53353667,  1.1814507 , -0.53034024,
        0.9421758 , -1.34482997, -0.48744434, -0.35105988, -0.52067778,
        1.10055402, -1.151769  ,  0.56502549, -1.02925015, -1.17452212,
        0.0029486 , -0.07040793, -0.40728131,  0.53118494, -1.06206826])

In [85]:
np.arange(0,1.01,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [55]:
#create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [73]:
mat = np.arange(1,26).reshape(5,5)
mat_copy = mat.copy()
mat_copy2 = mat.copy()
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [66]:
mat[3,4]

20

In [72]:
mat_copy[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [74]:
mat_copy2[4:]

array([[21, 22, 23, 24, 25]])

In [77]:
np.sum(mat)

325

In [82]:
#sum of all the columns in mat
np.sum(mat,axis = 0)

array([55, 60, 65, 70, 75])

In [84]:
#get the standard deviation of the values in mat
np.std(mat)

7.211102550927978